---
current_date: "{{ '%Y-%m-%d' | strftime }}"
current_ts: "{{ '%Y-%m-%d_%H-%M-%S' | strftime }}"
currentDate: "{{ lookup('pipe','date +%Y%m%d') }}"
date_compact: "{{ '%Y%m%d' | strftime }}"

db_name: DB0609
ENV_HOME: "/home/oracle"
ENV_FILE: "db.env"
log_dir: "/u01/app/oracle/backups"
tmp_sql_dir: "/u01/app/oracle/backups"
spool_log: "/u01/app/oracle/backups"

backup_threshold_hours: 96

localhost_log_path: "/var/lib/awx/projects/DBCS"
short_hostname: "{{ inventory_hostname.split('.')[0] }}"
local_log_file_path: "{{ localhost_log_path }}/{{ short_hostname }}"

GRID_ENV_HOME: "/home/grid"
GRID_ENV_FILE: "GRID.env"

backup_dir: "/u01/app/oracle/backups"  #Homes backup dir

oracle_home: "/u01/app/oracle/product/23.0.0.0/dbhome_1"
grid_home: "/u01/app/23.0.0.0/grid"

backup_homes:
  - oracle_home
  - grid_home

grid_patch_version: "23.26.3.0.0"
db_patch_version: "23.26.3.0.0"

smtp_server: "centroid-com.mail.protection.outlook.com"
smtp_port: "25"
email_recipients:
  #- madhuravani.peddi@centroid.com
  # - Lakshmi.Sunanda@centroid.com
  # - vamshi.thandu@centroid.com
  # - pavan.maccha@centroid.com
   - naidu.chaitanya@centroid.com
email_sender: "oracle@cenoiadolam01.ad.centroid.com"

sendmail_path: "/usr/sbin/sendmail"
notification:
  smtp_host: "cenoiadolam01"
  smtp_port: 25
  smtp_username: ""
  smtp_password: ""
  smtp_secure: ""
  from_email: ""
  to_emails:
    - "madhuravani.peddi@centroid.com"
